name: Manual Run

on: [workflow_dispatch]

jobs:
  clone_and_copy_commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone and copy commits
        run: node make-commits.js
        env:
          ORIGINAL_REPO_URL: ${{ secrets.ORIGINAL_REPO_URL }}
          EMAIL: ${{ secrets.EMAIL }}
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
          TARGET_REPO_URL: ${{ secrets.TARGET_REPO_URL }}
